# Site settings
title: Chotot Web Standards
email: dev@chotot.vn
description: "Chotot Web Standards documentation"
baseurl: "chotot-web-standards"

# Build settings
theme: jekyll-theme-cayman

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
