name: Release Canary

on:
  push:
    branches:
      - canary

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: PNPM setup
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm build

      - name: Release Canary
        run: |
          pnpm release:canary
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
