name: Release Canary

on:
  push:
    branches:
      - canary

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release Canary
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: PNPM setup
        uses: pnpm/action-setup@v3
        with:
          version: 8.6.0
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: |
          pnpm build

      - name: Release Canary
        run: |
          pnpm release:canary
