name: Release
on:
  push:
    branches:
      - main
      - feat/update-release-flow

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write # needed for git push / creating tags
  pull-requests: write # needed to update PRs (title, body, labels, comments)

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      HOME: ${{ github.workspace }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: PNPM setup
        uses: pnpm/action-setup@v3
        with:
          version: 8.6.0

      - name: Log .npmrc BEFORE setup node
        run: |
          echo "--- .npmrc before setup node ---"
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Log .npmrc after setup node
        run: |
          echo "--- .npmrc after setup node ---"

      - name: test token .
        run: | 
          echo "HOME: $HOME"
          cat "$HOME/.npmrc"
          LEN=${#NPM_TOKEN}
          MASKED="${NPM_TOKEN:0:8}$(printf '%*s' "$((LEN-12))" '' | tr ' ' '*')${NPM_TOKEN: -4}"
          echo "TOKEN: $MASKED"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Dependencies
        run: pnpm install

      - name: Log .npmrc BEFORE publish
        run: |
          echo "--- .npmrc before publish ---"
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env: 
          HOME: ${{ github.workspace }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log .npmrc AFTER publish
        run: |
          echo "--- .npmrc after publish ---"