name: Release
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write # needed for git push / creating tags
  pull-requests: write # needed to update PRs (title, body, labels, comments)

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: 'actions/checkout@v4'
      - name: PNPM setup
        uses: 'pnpm/action-setup@v3'
        with:
          version: 8.6.0
      - name: Setup Node.js 22.x
        uses: 'actions/setup-node@v4'
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
      - name: Install Dependencies
        run: pnpm install
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm release
